development:
  adapter: mysql2
  encoding: utf8
  database: beard_development
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: beard_test
  pool: 5
  username: root
  password: root
