default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: beardedshame_development

test:
  <<: *default
  database: beardedshame_test

production:
  <<: *default
  database: beardedshame_production
  username: beardedshame
  password: <%= ENV['beardedshame_DATABASE_PASSWORD'] %>
